name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.46.2

      - name: Test
        run: make test

      - name: Upload results to codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
